name: Ação composta

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  testar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/preparar
      - run: python -m unittest -v
  empacotar:
    needs: testar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/preparar
      - run: python build.py
      - name: Conferir o arquivo gerado
        run: test -s dist/index.html
